### ISSUE TITLE
clone method for LogicTile

### ISSUE THREAD

**Issue by DaanSchar** [DaanSchar/bamboogame#69]
make sure that the type that Hexagon takes in implements some cloning interface, like clonable. this means that LogicTile needs to implement clonable.

**Comment by Jolijn2020** [comment]
not yet possible since logicTile contains references to other tiles and classes.
And cloning these classes is possible, it would let the current logicTile have the same neighbours and groupmembers and board, even though it is not supposed too (aka. changes to clone will effect other "original" LogicTiles.
